//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ncu.Oolab.Korat.KAutomation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ncu.Oolab.Korat.KAutomation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviors to be added should not be null..
        /// </summary>
        internal static string AddBehaviorsNullException {
            get {
                return ResourceManager.GetString("AddBehaviorsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automator should not be null..
        /// </summary>
        internal static string AutomatorNullException {
            get {
                return ResourceManager.GetString("AutomatorNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviors to be added already exists..
        /// </summary>
        internal static string BehaviorsAlreadyExistsException {
            get {
                return ResourceManager.GetString("BehaviorsAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BehaviorsPool instance should not be null..
        /// </summary>
        internal static string BehaviorsPoolNullException {
            get {
                return ResourceManager.GetString("BehaviorsPoolNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IScript instance should not be null..
        /// </summary>
        internal static string IScriptNullException {
            get {
                return ResourceManager.GetString("IScriptNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IServices instance should not be null..
        /// </summary>
        internal static string IServicesNullException {
            get {
                return ResourceManager.GetString("IServicesNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korat instance should not be null..
        /// </summary>
        internal static string KoratNullException {
            get {
                return ResourceManager.GetString("KoratNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service &quot;{0}&quot; to be registered already exists..
        /// </summary>
        internal static string ServiceAlreadyExistsException {
            get {
                return ResourceManager.GetString("ServiceAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The the requested service cannot be loaded and converted to type &quot;{0}&quot;..
        /// </summary>
        internal static string ServiceTypeLoadException {
            get {
                return ResourceManager.GetString("ServiceTypeLoadException", resourceCulture);
            }
        }
    }
}
